/**
 * Generated by SPARK103 (https://spark103.dev)
 * 103 Software Solutions LLC
 */

import { useNavigate } from 'react-router-dom'

export default function Landing() {
  const navigate = useNavigate()

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '40px 20px',
        background: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
      }}
    >
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: '1fr 1fr',
          gap: '60px',
          maxWidth: '1200px',
          width: '100%',
          alignItems: 'center',
        }}
      >
        {/* Left Column - Content */}
        <div style={{ textAlign: 'left' }}>
          {/* Heading */}
          <h1
            style={{
              fontSize: '56px',
              fontWeight: 700,
              color: '#1a2744',
              marginBottom: '12px',
              fontFamily: 'Fraunces, serif',
              margin: 0,
            }}
          >
            Ledger
          </h1>

          <p
            style={{
              fontSize: '24px',
              color: '#5a7a8a',
              marginBottom: '24px',
              fontFamily: 'Inter, sans-serif',
              fontWeight: 600,
            }}
          >
            Plan. Organize. Pace.
          </p>

          {/* Description */}
          <p
            style={{
              fontSize: '16px',
              lineHeight: '1.8',
              color: '#444',
              marginBottom: '32px',
              fontFamily: 'Inter, sans-serif',
            }}
          >
            A beautifully designed lesson planner for educators who want to create, organize,
            and pace their lesson plans with intention. Built solo-first, designed to scale.
          </p>

          {/* Features List */}
          <div style={{ marginBottom: '40px' }}>
            <div style={{ marginBottom: '16px', display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
              <span style={{ fontSize: '20px', color: '#5a7a8a' }}>✓</span>
              <div>
                <p style={{ margin: 0, fontWeight: 600, color: '#1a2744', marginBottom: '4px' }}>Create & Organize</p>
                <p style={{ margin: 0, fontSize: '14px', color: '#666' }}>Build comprehensive lesson plans with objectives, materials, assessments, and differentiation.</p>
              </div>
            </div>
            <div style={{ marginBottom: '16px', display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
              <span style={{ fontSize: '20px', color: '#5a7a8a' }}>✓</span>
              <div>
                <p style={{ margin: 0, fontWeight: 600, color: '#1a2744', marginBottom: '4px' }}>Pacing Calendar</p>
                <p style={{ margin: 0, fontSize: '14px', color: '#666' }}>See your lessons across a week view to pace instruction and manage timing effectively.</p>
              </div>
            </div>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
              <span style={{ fontSize: '20px', color: '#5a7a8a' }}>✓</span>
              <div>
                <p style={{ margin: 0, fontWeight: 600, color: '#1a2744', marginBottom: '4px' }}>Standards Aligned</p>
                <p style={{ margin: 0, fontSize: '14px', color: '#666' }}>Tag lessons with curriculum standards and track alignment across your grade or subject.</p>
              </div>
            </div>
          </div>

          {/* CTA Button */}
          <button
            onClick={() => navigate('/dashboard')}
            style={{
              padding: '14px 40px',
              fontSize: '16px',
              fontWeight: 600,
              color: '#fff',
              background: '#1a2744',
              border: 'none',
              borderRadius: '8px',
              cursor: 'pointer',
              transition: 'all 0.3s ease',
              fontFamily: 'Inter, sans-serif',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = '#0d1828'
              e.currentTarget.style.transform = 'translateY(-2px)'
              e.currentTarget.style.boxShadow = '0 8px 16px rgba(0,0,0,0.2)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = '#1a2744'
              e.currentTarget.style.transform = 'translateY(0)'
              e.currentTarget.style.boxShadow = 'none'
            }}
          >
            Start Planning
          </button>
        </div>

        {/* Right Column - Visual */}
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            justifyContent: 'center',
            gap: '24px',
          }}
        >
          <div style={{
            background: 'rgba(255,255,255,0.8)',
            borderRadius: '16px',
            padding: '40px',
            boxShadow: '0 8px 32px rgba(0,0,0,0.1)',
            textAlign: 'center',
          }}>
            <img
              src={ledgerLogo}
              alt="Ledger"
              style={{ height: '280px', width: 'auto' }}
            />
          </div>

          <div style={{
            background: 'rgba(255,255,255,0.6)',
            borderRadius: '12px',
            padding: '20px 24px',
            textAlign: 'center',
            backdropFilter: 'blur(10px)',
          }}>
            <p style={{ margin: 0, fontSize: '14px', color: '#555', fontFamily: 'Inter, sans-serif' }}>
              <span style={{ fontWeight: 600, color: '#1a2744' }}>Trusted by educators</span><br />
              who care about intention and clarity
            </p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div
        style={{
          position: 'absolute',
          bottom: '60px',
          left: '50%',
          transform: 'translateX(-50%)',
          textAlign: 'center',
        }}
      >
        <p
          style={{
            fontSize: '12px',
            color: '#888',
            fontFamily: 'Inter, sans-serif',
            margin: 0,
          }}
        >
          Built with SPARK103 — Imagination → Spark → Innovation → Creation
        </p>
      </div>
    </div>
  )
}
