/**
 * Generated by SPARK103 (https://spark103.dev)
 * 103 Software Solutions LLC
 */

export default function Footer() {
  return (
    <footer
      style={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        padding: '12px 16px',
        background: 'rgba(0,0,0,0.05)',
        borderTop: '1px solid rgba(0,0,0,0.1)',
        fontSize: '11px',
        color: '#666',
        textAlign: 'center',
        zIndex: 1000,
        pointerEvents: 'none',
      }}
    >
      © 2026 Ledger. SPARK103 is a product of 103 Software Solutions LLC. All Rights Reserved.
    </footer>
  );
}
