/**
 * Generated by SPARK103 (https://spark103.dev)
 * 103 Software Solutions LLC
 */

import spark103Mark from '../assests/spark103-mark.png'

export default function Spark103Badge() {
  return (
      <a
        href="https://spark103.dev"
        target="_blank"
        rel="noopener noreferrer"
        aria-label="Made with SPARK103"
        style={{
          position: 'fixed',
          bottom: '16px',
          right: '16px',
          display: 'flex',
          alignItems: 'center',
          gap: '6px',
          padding: '8px 12px',
          borderRadius: '8px',
          background: 'rgba(0,0,0,0.85)',
          textDecoration: 'none',
          border: '1px solid rgba(255,255,255,0.1)',
          transition: 'all 0.2s ease',
          zIndex: 9999,
        }}
        onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(0,0,0,0.95)'}
        onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(0,0,0,0.85)'}
      >
        <img
          src={spark103Mark}
          alt=""
          width="16"
          height="16"
          style={{ borderRadius: '50%' }}
        />
        <span style={{ color: '#fff', fontSize: '10px', fontWeight: 600, lineHeight: '1.3' }}>
          © SPARK103, a product of 103 Software Solutions LLC. All Rights Reserved.
        </span>
      </a>
  );
}
