/**
 * Generated by SPARK103 (https://spark103.dev)
 * 103 Software Solutions LLC
 */

export function Spark103Watermark() {
  return (
    <a
      href="https://spark103.dev"
      target="_blank"
      rel="noopener noreferrer"
      className="spark103-badge"
      aria-label="Made with SPARK103 a product of 103 Software Solutions LLC."
      style={{
        position: "fixed",
        bottom: 16,
        right: 16,
        zIndex: 9999,
        display: "flex",
        alignItems: "center",
        gap: 6,
        padding: "6px 12px",
        borderRadius: 999,
        background: "rgba(0,0,0,0.85)",
        textDecoration: "none",
        boxShadow: "0 0 18px rgba(167, 139, 250, 0.28)",
      }}
    >
      <img
        src={`${import.meta.env.BASE_URL}spark103-mark.png`}
        alt=""
        width={36}
        height={36}
        style={{
          borderRadius: "50%",
          objectFit: "contain",
          flexShrink: 0,
          background: "#050508",
        }}
      />
      <span style={{ color: "#fff", fontSize: 11, fontWeight: 600, lineHeight: 1.3 }}>
        Made with SPARK103 a product of 103 Software Solutions LLC.
      </span>
    </a>
  );
}
